### ISSUE TITLE
validatie

### ISSUE THREAD

**Issue by ElsLommelen** [inbo/dhcurve#23]
In hoeverre is het nodig om bij de validatie ook de verdeling van de metingen over de verschillende omtrekklassen te checken?
Mogelijke problemen:
- weinig metingen in meerdere opeenvolgende omtrekklassen in begin of einde (bv. zomereik gavers)
- 2 aparte groepen metingen en niks in tussenliggende omtrekklassen

**Comment by ElsLommelen** [comment]
Zou kunnen getest worden door chisq.test, waarbij de verdeling over de omtrekklassen bekeken wordt: zie Pearsons chi-squared test op [https://en.wikipedia.org/wiki/Chi-squared_test](https://en.wikipedia.org/wiki/Chi-squared_test), waarbij x het aantal metingen van de omtrekklasse is, en m het totaal aantal metingen gedeeld door het aantal omtrekklassen van het interval.

Maar lijkt overbodig met alle andere test: kans is klein dat deze er niet uitgevist worden.

Eventueel wel adviseren: alle curves afdrukken en naar respectievelijke beheerders sturen als foutcontrole.

**Comment by leymanan** [comment]
Misschien toch wel nuttig, want het zijn ca 1570 curves die bekeken moeten worden.
Allez, hangt ervan af hoe moeilijk te programmeren (of eerder hoeveel tijd dat inneemt). Misschien weegt het niet op.

Want ik ben niet zo zeker of de kans effectief klein is dat deze er niet uitgevist worden (door te focussen op holle of bolle curves ...)
Al zeker niet wanneer het afgeleide curves betreft.

Wou het aangeven, maar misschien is dat iets om te bespreken met Thierry (of het sop de kolen waard is).

**Comment by ElsLommelen** [comment]
Ter info: ik had dat destijds met Thierry besproken (nadat ik de vraag in de eerste textbox gepost had), en de tweede tekstbox reflecteert in 't kort wat toen besproken is.  Hij gaf dus toen aan dat het sop de kool waarschijnlijk niet waard was.

Voor de volledigheid: behalve holle en bolle curves zijn er ook andere zaken die bovenstaande problemen vermijden of zorgen dat ze eruit gevist worden:
- de berekening van het bruikbaar interval is zodanig dat weinig metingen bij de eerste en laatste klassen vermeden worden, dus het eerste probleem komt zeer weinig voor (en als het voorkomt, wordt het gedetecteerd door de curvevorm)
- bij de 2 aparte groepen metingen heb je veel kans dat er tamelijk wat punten als afwijkend ingekleurd zijn, en dat die onder de categorie 'hoge RMSE' vallen, en ook dat wordt vaak aangevuld met een afwijkende curvevorm...
- afgeleide curves zijn gebaseerd op het Vlaams model (wat gebaseerd is op heel veel gegevens van meestal goede modellen) en ze hebben daardoor per definitie een 'mooie vorm' (zonder hol of bol).  Hier is eigenlijk de redenering vrij simpel: die curve wordt midden in de puntenwolk gelegd, een zwaardere modelbouw laat dit beperkt aantal gegevens niet toe (de zgn. noodoplossing).  Hier zou je je evt. op die categorie 'hoge RMSE' kunnen baseren om de 'slechtste' modellen eruit te halen, die je wat grondiger wil bekijken (dat gaan vaak de modellen zijn waar een groep metingen afwijkt van de rest).

Zelf heb ik destijds ook alle grafieken bekeken om te zien hoe waterdicht de huidige procedure was, en die probleemgevallen werden inderdaad allemaal gedetecteerd en in het validatierapport opgenomen met afwijkende curve.

Ik heb net ook even de probleemgevallen met 2 groepen metingen bekeken die je doorgemaild hebt, en ik vraag me eigenlijk af of die Pearsons chi-squared test deze voorbeelden wel als afwijkend zou detecteren: als je enkel naar de omtrekklassen kijkt, lijken de verschillende groepen metingen (die wij visueel onderscheiden op basis van de hoogtes) volledig te overlappen, wat naar mijn inschatting zal resulteren in een min of meer gelijk aantal metingen voor elke omtrekklasse.  Dus zou die test in deze gevallen iets detecteren?  Anderzijds werden beide curves er wel uitgepikt op basis van hun afwijkende vorm...

Ik vrees dus dat die extra test weinig meerwaarde heeft.  Voor alle duidelijkheid: het is niet de bedoeling om die 1570 curves allemaal te bekijken, het is enkel de bedoeling om de afwijkende curves in de validatierapporten te bekijken en hiermee zou je alle probleemgevallen dus moeten gecontroleerd hebben.  De rest zou in orde moeten zijn.  (Voor de afgeleide modellen dus misschien best die met hoge RMSE controleren, maar die gaan dus nooit zo goed kunnen zijn dan de basismodellen omwille van het beperkt aantal gegevens...)

**Comment by leymanan** [comment]
OK!

Bedankt voor uitvoerige toelichting!! Geeft me wat geruster gevoel.

**Comment by leymanan** [comment]
je zegt "_op het moment wil je die goedgekeurde curves niet meer zien, maar zodra er gegevens toegevoegd worden aan de databank, wil je uiteraard dat die curves weer wel getoond worden als ze afwijkend zijn (de afwijking kan groter zijn, waardoor je ze mss toch wel beter zou afkeuren, al is ze hopelijk minder groot)_."

Dat is inderdaad een aandachtspunt.
Maar sowieso moet ik daar een oplossing voor hebben: ik zet in mijn databank dat die bepaalde curve goedgekeurd is. Als ik dan initiatie laat lopen, ga ik niet meer kijken naar die "goedgekeurde" curve (maakt niet uit of ze nu wel of niet in het validatierapport zit).
Ik zal sowieso een script moeten aanmaken dat ervoor zorgt dat voor alle curves waar nieuwe gegevens bijkomen, de status terug naar "te controleren" gezet wordt

**Comment by ElsLommelen** [comment]
Eventjes je tekstje hier toevoegen, om een of andere reden is dat hier niet terechtgekomen:

je zegt "_op het moment wil je die goedgekeurde curves niet meer zien, maar zodra er gegevens toegevoegd worden aan de databank, wil je uiteraard dat die curves weer wel getoond worden als ze afwijkend zijn (de afwijking kan groter zijn, waardoor je ze mss toch wel beter zou afkeuren, al is ze hopelijk minder groot)._"

Dat is inderdaad een aandachtspunt.
Maar sowieso moet ik daar een oplossing voor hebben: ik zet in mijn databank dat die bepaalde curve goedgekeurd is. Als ik dan initiatie laat lopen, ga ik niet meer kijken naar die "goedgekeurde" curve (maakt niet uit of ze nu wel of niet in het validatierapport zit).
Ik zal sowieso een script moeten aanmaken dat ervoor zorgt dat voor alle curves waar nieuwe gegevens bijkomen, de status terug naar "te controleren" gezet wordt

**Comment by ElsLommelen** [comment]
Mss gaat een analoog van `Uitzonderingen` bij `initiatie()` met een aantal metingen toch een oplossing zijn?  Of op basis van datums ofzo?

Hoe ga je dit eigenlijk opvolgen?  Ga je dit vaak bekijken n.a.v. extra metingen bij 1 domein?  (In dit geval kan je gemakkelijk gericht dat ene domein updaten.)  Of ga je dit pakweg eens per jaar updaten?  En is er in zo'n periode veel toegevoegd?  Ik veronderstel dat als er extra metingen zijn voor een bepaald domein, dat dat meestal niet over 1 meting per BMS gaat maar over meerdere?  (Een beetje praktische info kan me helpen om na te denken over de beste optie.  Als dit wat veel is om allemaal op te sommen, kunnen we er ook over samenzitten.)

**Comment by leymanan** [comment]
dat stukje tekst had ik daar per ongeluk gezet, maar vrij snel gedelete en onder issue36 geplaatst. Sorry!

**Comment by leymanan** [comment]
Opvolging: nog niet echt over nagedacht, ik heb het er wel al kort met Martine over gehad, en mogelijks kunnen we wel iemand inschakelen om gericht extra metingen te doen.  Maar dat zal geen ganse ploeg zijn die direct een massa domeinen afhandelt.

Maar hoe snel die data gaat binnenkomen, dat weet ik eigenlijk niet. Mogelijks doe ik dat domein per domein, maar lijkt me anderzijds voor mijn eigen werklast beter om dat 1 of max. 2 keer per jaar bij te werken, voor een aantal domeinen tegelijk. 

En inderdaad: kans dat dat maar één boomsoort per domein is, is klein.

**Comment by leymanan** [comment]
Eigenlijk zie ikzelf geen groot probleem in het aanpassen van de status van curves waar extra metingen voor voorhanden zijn (terugzetten naar "Niet gecontroleerd".
Wat ik me nu wel afvraag is of dat ook nodig is voor de andere modellen (basis en afgeleid) die gebaseerd zijn op het Vlaams model: daar komen - per bms - dan ook extra metingen bij wat curve kan veranderen?

**Comment by ElsLommelen** [comment]
Theoretisch kan dat Vlaams model uiteraard wel veranderen, maar in de praktijk gaan enkele honderden metingen (verspreid over meerdere BMS) die Vlaamse curves nog amper beïnvloeden, zeker niet voor soorten die in grote aantallen opgemeten zijn in bv. Zoniën, Meerdaal en/of Ravels.  Als je veel metingen van een minder talrijke boomsoort toevoegt (of bv. eentje met vaak afwijkende curves zoals cultuurpopulier) en je ziet dat de curve in kwestie grondig verandert, dan is het uiteraard wel raadzaam om alle (afwijkende) curves van die BMS opnieuw te controleren.  En mss wil je om de x aantal jaren toch nog eens alles herbekijken, bv. n.a.v. het toevoegen van een groot aantal metingen?

In de praktijk zou ik bij mijn idee van issue #36 wel alles opnieuw berekenen, dus de aanpassing zou enkel invloed hebben op het tonen van de curves in het validatierapport, niet op de berekening en het eindresultaat.

Anderzijds denk ik ook dat het belangrijk is om in het script enkel die curves toe te voegen waarvoor het nodig is, dus de curves die **in de validatierapporten als afwijkend aangeduid zijn** en afgekeurd (voor uitzonderingen) of goedgekeurd (voor validatierapport) zijn.  Het is uiteraard te vermijden om dit lijstje langer te maken dan strikt nodig (in je script, uiteraard kan je in je databank wel een vollediger lijstje hebben, zolang je de relevante records er maar uit filtert).  Verder lijken deze afwijkende curves (samen met curves met te weinig metingen) me prioritaire domeinen om bijkomende metingen te doen, dus idealiter wordt dat lijstje stilaan korter en korter.

**Comment by ElsLommelen** [comment]
Euh, dit issue mag ook dicht, neem ik aan?
