### ISSUE TITLE
nog te bespreken

### ISSUE THREAD

**Issue by ElsLommelen** [inbo/dhcurve#26]
- naamgeving: Q5k en Q95k (klassemidden van 2.5 en 97.5 % BI) hernoemen?
- databank: praktisch voor foutcontrole om 1 ID te hebben
- 'Hoofdscript' misschien best uit package halen? --> eenvoudiger aan te passen (basis hiervan staat ook in vignette)

**Comment by ElsLommelen** [comment]
i.v.m. Hoofdscript: als dit uit package gehaald wordt, is functie leesfile waarschijnlijk ook niet meer nodig.

**Comment by leymanan** [comment]
van mij mag hoofdscript uit package gehaald worden!

**Comment by ElsLommelen** [comment]
Voila, daarmee is dit issue ook opgelost, denk ik:
> - naamgeving: Q5k en Q95k (klassemidden van 2.5 en 97.5 % BI) hernoemen?

Op ons eerste overleg dit najaar gaf je aan dat je dit niet nodig vond
> - databank: praktisch voor foutcontrole om 1 ID te hebben

Deze ID heb je toegevoegd
> - 'Hoofdscript' misschien best uit package halen? --> eenvoudiger aan te passen (basis hiervan staat ook in vignette)

Dit heb ik dus net gedaan.
