### ISSUE TITLE
style

### ISSUE THREAD

**Issue by ElsLommelen** [inbo/dhcurve#29]
De stijl van de namen is niet consequent:
- deel camelCase en CamelCase
- deel dotted.case
- maar ook deel mix van beiden

Evt. consequent voor 1 stijl kiezen (evt. zelfs meteen snake_case) en aanpassen vooraleer het package gebruikt wordt?

**Comment by leymanan** [comment]
ik zou daar onze/jouw tijd niet insteken ;-)

**Comment by ElsLommelen** [comment]
Inderdaad, was al gezegd tijdens ons eerste overleg.  'k Zal het issue sluiten.
