### ISSUE TITLE
DomeincurveDynamisch.Rmd

### ISSUE THREAD

**Issue by leymanan** [inbo/dhcurve#32]
aan te passen:
- rode en zwarte kleur omwisselen
- ID van tooltip is steeds dezelfde, varieert niet per dot
(? zou het handiger zijn om ID van bomen IDtree te noemen?)
- eventueel omtrek toevoegen (naast ID en hoogte)

**Comment by ElsLommelen** [comment]
> - rode en zwarte kleur omwisselen

aangepast
> - ID van tooltip is steeds dezelfde, varieert niet per dot

Fout opgelost.  Ik merk wel dat bij de punten van het model de ID van de dichtstbijzijnde meting overgenomen wordt.  Idee van de tooltip is vooral om de outliers te bekijken, dus houd dat best in gedachten.
>   (? zou het handiger zijn om ID van bomen IDtree te noemen?)

Een ID voor elke meting is even duidelijk en handig, lijkt mij (en dat vermijdt een semantische kwestie als je ooit eenzelfde boom opnieuw meet).  Het maakt ook je tooltip-venstertje niet nodeloos groot.
> - eventueel omtrek toevoegen (naast ID en hoogte)

Ok, toegevoegd.  Merk op dat de punten met een jitter uit elkaar gehaald zijn, dus je kan die omtrek ook gemakkelijk onderaan de grafiek aflezen.

**Comment by leymanan** [comment]
Bedankt! Dit lijkt me OK, maar kan ik blijkbaar niet controleren, ik krijg op dit moment een blanco html.
Wellicht moet ik eerst de rest van de issues doorlopen en pull request #42 aanvaarden
