### ISSUE TITLE
toevoegen van BoomsoorttypeID aan IVANHO output

### ISSUE THREAD

**Issue by leymanan** [inbo/dhcurve#38]
om de curves te kunnen gebruiken in IVANHO moet - naast omtrekklassetypeID - ook BoomsoorttypeID toegevoegd worden.
Misschien moet er daartoe al van in het begin overgestapt worden naar de boomsoorten gebruikt in IVANHO.
Ik heb dat nu reeds zo geïmplementeerd in mijn hoofdscript.
Maar in de functie "OutputIVANHO.R" zou naast het veld "BMS" ook het veld "BoomsoorttypeID" moeten opgenomen zijn.

De link tss bms in bosdat en deze in IVANHO is te vinden in de tabel "lkpLinkBmsIvanhoBosdatOpmaakCurve" in de db met meetgegevens.
Eigenlijk moeten enkel de boomsoorten waar TerOpmaakCurve = TRUE is, meegenomen worden.

Makkelijkste is volgens mij om reeds bij de start te werken met de boomsoorten uit IVANHO en de query om data in te laden in die zin aan te passen.
(zie ev. ook mijn hoofdscript in "https://github.com/leymanan/dhcurves_ANB")

**Comment by ElsLommelen** [comment]
Euh, ik zag niet goed wat je aangepast had in het hoofdscript, maar inderdaad is het logisch dat je van in het begin de boomsoorten meegeeft die je nodig hebt (dus deze uit IVANHO), zeker als bepaalde soorten geclusterd worden (als ze een 1-op-1-relatie hebben, maakt het minder uit).

Ik zie dat er momenteel in het package een variabele `IDbms` gebruikt wordt die niet uitgevoerd wordt.  Is het ok om deze te gebruiken om de inhoud van BoomsoorttypeID in te vullen (en dan kan je deze na de berekeningen omzetten voor gebruik in IVANHO)?  De variabelenaam doorheen het hele package - inclusief documentatie - aanpassen, is zeer veel werk; de variabele `IDbms` uitvoeren in bij de functie `outputIVANHO()` vraagt veel minder werk (in de documentatie van 1 functie, en aanwezigheid van die variabele moet waarschijnlijk gecheckt worden om errors te vermijden).

Vermits `BMS` en `BoomsoorttypeID` gelinkt zijn, is het ook een optie om het package te laten zoals het is en dat je achteraf `BoomsoorttypeID` koppelt aan `BMS`.

**Comment by leymanan** [comment]
Voor mij OK om bmsID te gebruiken.
En dit enkel aan te passen in de functie outputIVANHO(), dat moet niet in hele package gebruikt worden, dat was ook niet mijn bedoeling.

Maar is het niet mogelijk om helemaal op einde van functie outputIVANHO(), dat veld een andere naam te geven (nl. "BoomsoorttypeID")?
Dan is de output voor IVANHO direct in orde en klaar voor import in IVANHO.


Ik kan dat natuurlijk ook nog doen in een R-script, geen probleem?. Maar is wel een output dat heel veel gaat gebruikt worden, en dan lijkt het me nuttig dat de velden direct de juiste naam hebben.

Waarom ik liever niet achteraf de koppeling leg tss  BMS en BoomsoorttypeID , is dat dit echt wel een essentieel deel van de output is, en ik wil niet dat er ooit fouten insluipen door foute koppeling ...

**Comment by leymanan** [comment]
Of begrijp ik iets niet?

**Comment by ElsLommelen** [comment]
Misschien was ik een kleinigheidje vergeten te vermelden: de naam 'tijdens de berekening' veranderen van `IDbms` naar `BoomsoortteypeID` zou ik niet doen omdat dit me verwarrend lijkt voor eventuele andere gebruikers die het package zouden gebruiken: ze voeren een variabele in, en die komt er onder een andere naam terug uit...  Dus ik zou ofwel alles aanpassen naar `BoomsoorttypeID`, ofwel ook de uitvoer houden bij `IDbms`.

Dus dan toch maar alles aanpassen voor deze ene variabele?  (`BoomsoorttypeID` past wel iets minder bij `BMS` dan `IDbms`, maar `IDbms` aanpassen valt zo te zien nogal redelijk mee, `BMS` aanpassen zou waarschijnlijk veel meer werk zijn, dus ik ga niet voorstellen om deze ook aan te passen. ;-) )

**Comment by leymanan** [comment]
ja, dat snap ik, dat dat verwarrend is om naam tijdens berekening te veranderen!

Voor mij ook zeker OK om IDbms te houden, want ik moet toch nog andere velden aanpassen en GUID koppelen ...
Maar zou wel goed zijn mocht de ID erin zitten en niet enkel de naam voluit.

**Comment by leymanan** [comment]
super!
