### ISSUE TITLE
outputIVANHO.R: extra velden + naamgeving aanpassen

### ISSUE THREAD

**Issue by leymanan** [inbo/dhcurve#39]
de tabel die in IVANHO gebruikt wordt bevat volgende velden :
- AutomatischeHoogteberekeningParameterID = unieke ID
- BeheerindelingID = unieke GUID (zie #40 ) 
- BoomsoorttypeID (zie  #38)
- OmtrekklassetypeID (zit reeds in IVANHO.csv)
- StandaardHoogte = Hoogte
- Beheerindeling = BOS_BHI

Zie
[2017LkpLijsten_IVANHO_SamNeefs.xlsx] (https://github.com/inbo/dhcurve/files/5401468/2017LkpLijsten_IVANHO_SamNeefs.xlsx)
tabblad "Hoogtes"

Graag output in die zin aanpassen

**Comment by ElsLommelen** [comment]
Zie ook mijn antwoorden op issues #40 en #38.
Om dit te doen, zijn er 3 opties die zeer veel werk vragen en/of nodeloos complex zijn:

- naamgeving van een bepaalde variabele vervangen doorheen het hele package inclusief alle documentatie (bij andere afkorting liefst ook de teksten in die zin wat aanpassen, dus enkel search & replace is niet genoeg).  Als je het ziet zitten om dit te doen, ga zeker je gang, maar ik heb daar eerlijk gezegd geen tijd voor (anderen wachten ook op mijn hulp voor hun project...).
- deze als extra variabelen toevoegen (vereist extra informatie in de documentatie, en er moet minstens getest worden of die variabelen wel toegevoegd zijn).  Nadeel hiervan is dat deze variabelen vaak redundant zijn (een 1-op1-relatie hebben met andere variabelen), wat een groot nadeel is als anderen het package ooit willen gebruiken: ze zijn ook verplicht om al die overbodige variabelen te voorzien
- in de code van `outputIVANHO()` voor de output alle variabelen van de ingevoerde data overnemen behalve deze die gekend zijn in het package (bv. C13, HOOGTE , Status).  Klinkt gemakkelijk en flexibel naar gebruikers toe, maar dan kom je in de problemen met niet gekende variabelen die niet gegroepeerd zijn per BMS-domein-combinatie, zoals Jaar, TYPE_METING,...  Die zouden beter niet overgenomen worden, wat technisch perfect mogelijk is, maar het vraagt dus ook heelwat tijd om hier een waterdicht systeem van te maken...

Enfin, ik denk dat de beste optie hier is om je naamgeving te veranderen of gegevens te koppelen in je eigen script na uitvoeren van de functies (en evt creatief zijn door velden op te vullen met ID's i.p.v. tekst).  Zoals voorgesteld in issue #38, wil ik die `IDbms` wel uitvoeren in de functie `outputIVANHO()`, geef je dan daar even aan als je dat wil?

**Comment by leymanan** [comment]
OK!

Ik snap het, is inderdaad makkelijkste dat ik een extra stuk code schrijf in "main.R", waar ik de veldnamen aanpas zoals nodig voor IVANHO.

Ik moet dat toch doen om de laatste GUID te kunnen toekennen.

Maar wat betreft de IDBms: dat zou ik toch nog handig vinden, sorry.
