### ISSUE TITLE
output IVANHO - betrouwbaarheidsinterval toevoegen

### ISSUE THREAD

**Issue by leymanan** [inbo/dhcurve#41]
vraagje: is het mogelijk om naast de hoogte per omtrekklasse, ook een betrouwbaarheidsinterval toe te voegen?
Of lukt dat niet met die mixed models?

**Comment by ElsLommelen** [comment]
Ik kan het betrouwbaarheidsinterval (BI) toevoegen, ofwel de RMSE (= equivalent van standaard error voor curves), op basis waarvan je zelf het BI kan berekenen (Hoogte - 2,5 * RMSE, Hoogte + 2,5 * RMSE).  Aan u de keuze.  Ingeval van BI, hoe zal ik de variabelen noemen?  OBI voor de ondergrens van het betrouwbaarheidsinterval en BBI voor bovengrens van het betrouwbaarheidsinterval, of heb je een beter idee?

**Comment by ElsLommelen** [comment]
Ik heb alvast de RMSE toegevoegd, omdat deze ook nodig was voor issue #36

**Comment by leymanan** [comment]
Kan je beide toevoegen: RMSE en BI?
BI_ondergrens en BI_bovengrens?
Ik weet dat dat wat langer is, maar misschien wel duidelijker voor "leken".
(wordt ook gebruikt bij VBI, dus voor mij ook zeer leesbaar ;-) )

**Comment by ElsLommelen** [comment]
Ok, is idd duidelijker dan mijn voorstel.  En de lengte maakt (voor de code in het package) wat minder uit, omdat de variabelen toch pas finaal berekend worden.

(Over de stijl van de namen ga ik me niet uitspreken - hoofdletters gecombineerd met underscores is geen bestaande stijl -, maar het past wel in de regel 'variabelen beginnen met een hoofdletter en functies met een kleine letter' en bij de wat gemixte stijl die in dit package gehanteerd wordt.  Ter info: voor de intussen afgesproken INBO-stijl zouden het allemaal kleine letters moeten zijn, moest je eens aan een ander INBO-package meewerken...)

**Comment by ElsLommelen** [comment]
Voila, toegevoegd.

**Comment by leymanan** [comment]
Bedankt
