### ISSUE TITLE
installatie-instructies toevoegen

### ISSUE THREAD

**Issue by ElsLommelen** [inbo/dhcurve#64]
via inbo-r-universe en via remotes::install_github, toevoegen aan readme

**Comment by ElsLommelen** [comment]
@leymanan vraagje in verband hiermee: idee is om op github en de website dezelfde installatie-instructies toe te voegen als [hier](https://github.com/inbo/inbodb#readme).  Voordeel van die inbo-r-universe is dat als je `install.packages()` gebruikt voor de installatie, je ook bij `update.packages()` een update krijgt van die packages, wat na installatie van een nieuwe R-versie handig is, want anders vergeet je die zelfgemaakte packages opnieuw te installeren.  Vermits er geen anb-r-universe bestaat, gaan we dan wel naar inbo-r-universe moeten verwijzen.  Ik hoop dat dit geen probleem is?

Je mag in elk geval kiezen of je die badges van r-universe er al dan niet bij wil.

**Comment by leymanan** [comment]
geen probleem dat dat inbo-r-universe is!
