### ISSUE TITLE
master naar main

### ISSUE THREAD

**Issue by ElsLommelen** [inbo/dhcurve#66]
@leymanan Ik wou het package dhcurve nog even opnemen voor enkele kleine aanpassingen (voor zover mogelijk alle openstaande issues), en ik zie dat hier nog een `master` branch in staat.  Deze zou ik om ethische redenen graag hernoemen naar `main` (`master` is tegenwoordig politiek incorrect vermits het verwijst slavernij, vandaar dat GitHub die basisbranch tegenwoordig default `main` noemt, en het ook relatief gemakkelijk gemaakt heeft om die naam aan te passen).  Is dit ok voor u?

Wat dit concreet inhoudt voor u:
- als je na de aanpassing naar deze repo op github surft, zal je een opmerking krijgen dat de master hernoemd is naar main, en je zal een beetje git-code krijgen die je kan kopiëren
- je zal dan lokaal je repo moeten opendoen en die code in de git shell plakken en uitvoeren (enter niet vergeten!).
- en vanaf dan zal alles main zijn i.p.v. master, en als je nog master gebruikt, krijg je een foutmelding (de INBO-handleidingen zijn trouwens ook aangepast)

Mogelijke alternatieven zijn:
- lokaal naar de develop gaan, met pull de main binnenhalen, en als de master niet vanzelf verdwijnt, die wegdoen met een git-commando
- gitrepo lokaal wissen en opnieuw binnenhalen

Zodra ik de aanpassing gemaakt heb, pas je dit uiteraard liefst zo snel mogelijk lokaal aan bij u.  (Dat duurt maar 5 minuten ofzo, mss een kwartiertje als je het nog nooit gedaan hebt en je je grondig wil inlezen voor je het doet.)  Want als je dit vergeet en pakweg over een half jaar in de repo gaat werken, ga je rare foutmeldingen krijgen en dan gaan we de link met die aanpassing mss niet meer direct leggen...

Is het ok voor u dat ik deze aanpassing maak?

**Comment by leymanan** [comment]
OK!
