### ISSUE TITLE
foutmelding bij gebruik outputIVANHO() met uitbreiding

### ISSUE THREAD

**Issue by leymanan** [inbo/dhcurve#72]
Ik krijg een foutmelding bij gebruik onderstaande code

```
uitbr_basis <- validatie.uitbreiding(Basismodel, Data.basis)
uitbr_lokaal <- validatie.uitbreiding(Lokaalmodel, Data.lokaal)

uitbr <- rbind(uitbr_basis, uitbr_lokaal)

OutputIvanho_uitbreiding <-
  outputIVANHO(Basismodel, Afgeleidmodel, Lokaalmodel, Data.lokaal, Uitbreiding = uitbr)

Error: Elke waarde van MaxOmtrek in de dataframe Uitbreiding moet groter zijn dan 2.4 (de minimumgrens voor een uitbreiding)
```

**Comment by ElsLommelen** [comment]
Lijkt me logisch dat het pas zin heeft om een uitbreiding te berekenen als er omtrekken zijn die groter zijn dan 2.4.  Kan je iets meer uitleg geven over het geval waarbij de uitbreiding kleiner is dan 2.4?  Is dit een domein waarbij er 10 metingen zijn tussen 2.3 en 2.4 m?

En hoe pak ik het best aan?  Zorg ik dat er in dit geval geen uitbreiding berekend wordt, omdat het niet de moeite is om die hele validatie te doorlopen voor die ene extra omtrekklasse?  Of wil je die toch wel meenemen, en pas ik die error hier aan?

**Comment by leymanan** [comment]
uitbreidingen zijn eigenlijk net belangrijk voor deze waar de metingen binnen bruikbaar interval maar tot bv. 1m gaan. Wat wil zeggen dat we geen info hebben over hoogtes binnen het interval 1m-2.4 m omtrek ..
Hierna twee voorbeeldjes: één waarbij bruikbaar interval maar tot 1 m gaat, en één (dat vrij veel voorkomt) met bruikbaar interval tot 1.65 (vaak 1.65, 1.75, 1.95, 2.05, ...)
![image](https://user-images.githubusercontent.com/26572532/223087416-5431506d-14fd-4b11-9c81-94c7b91bb0a8.png)
![image](https://user-images.githubusercontent.com/26572532/223087766-bc94c5e6-f88a-4668-9dec-9f6884b88429.png)

**Comment by leymanan** [comment]
> En hoe pak ik het best aan? Zorg ik dat er in dit geval geen uitbreiding berekend wordt, omdat het niet de moeite is om die hele validatie te doorlopen voor die ene extra omtrekklasse? Of wil je die toch wel meenemen, en pas ik die error hier aan?

Liefst wél de uitbreiding meenemen, want zijn toch vrij veel omtrekklasses

**Comment by ElsLommelen** [comment]
> uitbreidingen zijn eigenlijk net belangrijk voor deze waar de metingen binnen Q5-Q95-interval maar tot bv. 1m gaan. Wat wil zeggen dat we geen info hebben over hoogtes binnen het interval 1m-2.4 m omtrek ..

Ah, ok, dat was me eigenlijk niet duidelijk.  Ik dacht dat we deze uitbreidingen in de eerste plaats gemaakt hadden met het oog op extra uitbreidingen voor de domeinen met dikke bomen (bv. Zoniën).  Maar uiteraard ok om ze ook daarvoor te gebruiken, dan kan die foutmelding weg.

Moet er een foutmelding in de plaats komen die op een of andere manier checkt of die grens 'klopt' (bv. volgens de afspraak van issue #71 is)?  Of gaan we er van uit dat de gebruiker netjes de gegevens uit `validatie.uitbreiding()` overneemt en zijn eventuele aanpassingen hierin volledig zijn/haar verantwoordelijkheid?  (Er wordt uiteraard wel gecheckt of de opgegeven `MaxOmtrek` een klassemidden is.)

**Comment by leymanan** [comment]
Voor mij hoeft dat niet gecheckt te worden. 

Maar ev. wel ook in handleiding aanpassen ? 
"Bij voldoende gegevens in hogere omtrekklassen kan een model uitgebreid worden. Dit wil zeggen dat het eerder gefitte model toegepast wordt op hogere omtrekklassen **(tussen 2,4 en 3 m),** waarna het model bij deze hogere omtrekklassen gevalideerd wordt op basis van de metingen. "
Ev. vervangen door "op hogere omtrekklassen (> Q95k)"

**Comment by ElsLommelen** [comment]
Goed om me daar even aan te herinneren (ik check meteen alle documentatie).
