### ISSUE TITLE
validatie_uitbreiding met goedgekeurde curves

### ISSUE THREAD

**Issue by leymanan** [inbo/dhcurve#76]
Ik krijg foutmelding als ik functie validatie.uitbreiding met goedgekeurde functies doe

> names(uitbr_goedgekeurd_tmp)
[1] "DOMEIN_ID"            "BMS"                  "nExtra"              
[4] "nBomenTerugTonen"     "min_uitbreiden_model"

> uitbr_basis <- validatie.uitbreiding(Basismodel, Data.basis
+                                      , GoedgekeurdeUitbreidingen = uitbr_goedgekeurd_tmp)
Warning: Niet elk opgegeven record in GoedgekeurdeUitbreidingen heeft een afwijkende curveError in `filter()`:
! Problem while computing `..1 = is.na(.data$nBomenTerugTonen) | ...`.
Caused by error in `.data$nExtra`:
! Column `nExtra` not found in `.data`.
Backtrace:
  1. dhcurve::validatie.uitbreiding(Basismodel, Data.basis, GoedgekeurdeUitbreidingen = uitbr_goedgekeurd_tmp)
 12. rlang:::abort_data_pronoun(x, call = y)

**Comment by ElsLommelen** [comment]
Ah, oeps, ik had er geen rekening mee gehouden dat je weleens extra kolommen zou kunnen toevoegen die in conflict komen met het script (in dit geval de `nExtra`).  Ik hoop dat dit je probleem oplost?

(Die warning ga je wel blijven krijgen, maar hier heb ik de boodschap aangepast, blijkbaar had ik die ergens overgenomen en niet aangepast aan deze specifieke situatie.  Te negeren naar eigen keuze, dit is eerder informatief.)
