### ISSUE TITLE
foutmelding bij  dhcurvesrapport()

### ISSUE THREAD

**Issue by leymanan** [inbo/dhcurve#77]
Els, ik krijg volgende foutmelding

```
> dhcurvesrapport(
+   OutputIVANHO = OutputIvanho_def_,
+   Datalijst,
+   Bestandsnaam = "dhcurves_def.html",
+   verbose = TRUE,
+   PathWD = getwd()
+ )
Error: is.logical("KleurUitbreiding") is not TRUE
```

**Comment by ElsLommelen** [comment]
Die had ik daarstraks toevallig ook opgemerkt, en alvast opgelost in commit [591371c](https://github.com/inbo/dhcurve/pull/67/commits/591371ccb972067219090bf3b918700fd631f161).  Dus in de nieuwste versie zou dat in orde moeten zijn.
